import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import img3 from '@/app/asset/img3.jpg';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Welcome To Our Page",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen relative">
        
        {/* 🔥 Fixed Background Image */}
        <div className="fixed inset-0 -z-10">
          <Image
            src={img3}
            alt="background"
            fill
              className="object-cover blur-sm scale-110"
            priority
          />
          
          {/* Optional dark overlay */}
          <div className="absolute inset-0 bg-black/10" />
        </div>

        {/* 🔥 Scrollable Content */}
        <main className="relative z-10 p-6 space-y-10 backdrop-blur">
          {children}
        </main>

      </body>
    </html>
  );
}